AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-dispatch-router

  ECRRepositoryLambdaLB:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-dispatch-lambdalb

  ECRRepositoryDirectLambda:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-dispatch-directlambda
