name: "Configure Node.js"
description: "Install Node.js and install Node.js modules or restore cache"

inputs:
  lookup-only:
    description: "If true, only checks if cache entry exists and skips download. Does not change save cache behavior"
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Restore Node Modules from Cache
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          src/**/node_modules
          !node_modules/.cache
        key: node-modules-${{ inputs.node-version }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package.json', 'yarn.lock') }}
        lookup-only: ${{ inputs.lookup-only }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: yarn --frozen-lockfile
