name: PR Build and Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/configure-nodejs
        with:
          lookup-only: 'true' # We only want to lookup from the cache - if a hit, this job does nothing

  deploy:
    needs: [install-deps]
    runs-on: ubuntu-latest
    environment: ghpublic
    concurrency:
      group: deploy-${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: lambda-dispatch-ghpublic-build
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/builder-writeRole
          aws-region: us-east-2

      - uses: ./.github/actions/configure-nodejs

      - name: Build CDK Stack
        run: |
          yarn build

      - name: Deploy Stack
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          cd src/cdk-stack
          STACK_SUFFIX=${{ github.event_name == 'pull_request' && '-pr' || '' }}
          npx cdk deploy lambda-dispatch${STACK_SUFFIX} --require-approval never
